name: License Check

on:
  workflow_dispatch:

  push:
    branches: [ licence-check ]


#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install licensecheck
      run: pip install licensecheck

    - name: Check licenses
      run: |
        echo "Checking for disallowed licenses (GPL, LGPL, AGPL, Proprietary, Commercial)..."
        if ! python -m licensecheck \
          --file pyproject.toml \
          --fail-licenses GPL LGPL AGPL Proprietary Commercial \
          --only-licenses MIT Apache-2.0 BSD-2-Clause BSD-3-Clause ISC; then
          echo "::error::❌ License check failed! Found dependencies with disallowed licenses."
          echo "Please ensure all dependencies use permissive licenses (MIT, Apache-2.0, BSD, ISC)."
          exit 1
        fi
        echo "✅ All dependency licenses are compliant!"
