name: License Check

on:
  workflow_dispatch:

  push:
    branches: [ licence-check ]


#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install licensecheck
      run: pip install licensecheck

    - name: Check licenses
      run: |
        echo "Checking for disallowed licenses..."
        # Save the output to analyze it
        if ! python -m licensecheck > license_report.txt; then
          echo "::group::Found problematic licenses"
          grep -B 1 -A 1 "License:" license_report.txt | grep -v "^--$"
          echo "::endgroup::"
          echo "::error::❌ License check failed! Found dependencies with disallowed licenses."
          echo "Please ensure all dependencies use permissive licenses (MIT, Apache-2.0, BSD, ISC)."
          exit 1
        fi
        echo "✅ All dependency licenses are compliant!"
        echo "::group::License Report"
        cat license_report.txt
        echo "::endgroup::"
