name: License Check

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  license-check:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install licensecheck
      run: pip install licensecheck

    - name: Check licenses
      run: |
        echo "Checking for disallowed licenses..."
        echo "::group::License Report"
        python -m licensecheck --zero
        EXIT_CODE=$?
        echo "::endgroup::"
        
        if [ $EXIT_CODE -ne 0 ]; then
          echo "::error::❌ License check failed! Found dependencies with disallowed licenses."
          echo "Please ensure all dependencies use permissive licenses (MIT, Apache-2.0, BSD, ISC)."
          exit 1
        fi
        echo "✅ All dependency licenses are compliant!"
