name: Formatting (ruff)
on: [pull_request]
permissions:
  contents: read
  pull-requests: read
jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/ruff-action@v3
        with:
          version: "0.8.6"
      - uses: astral-sh/ruff-action@v3
        with:
          args: format --check --diff
          version: "0.8.6"
