name: Python Testing

on:
  pull_request:
    branches:
      - "*"

permissions:
  contents: write
  checks: write
  pull-requests: write

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "poetry"

      - name: install dependencies
        run: poetry install --all-extras

      # run unit tests first without env keys
      # this is to ensure we're not adding unit tests that need to call LLMs
      - name: unit_tests + coverage
        run: |
          set -o pipefail
          poetry run pytest tests/unit

      - name: tests + coverage
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          MISTRAL_API_KEY: ${{ secrets.MISTRAL_API_KEY }}
          PORTIA_API_KEY: ${{ secrets.PORTIA_API_KEY }}
        run: |
          set -o pipefail
          poetry run pytest --workers auto  --cov --cov-fail-under 100 --log-cli-level=WARNING --junitxml=pytest.xml | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
